FROM node:lts-alpine AS build

ARG FQ_IMAGE_GIT_SHA=unknown

LABEL org.opencontainers.image.revision="${FQ_IMAGE_GIT_SHA}"
LABEL io.freshquant.git_sha="${FQ_IMAGE_GIT_SHA}"

RUN npm config set registry https://registry.npmmirror.com
RUN npm install -g pnpm

RUN pnpm config set fetch-retries 5 && \
    pnpm config set fetch-retry-mintimeout 20000 && \
    pnpm config set fetch-retry-maxtimeout 120000

WORKDIR /fqwebui
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --prefer-offline --fetch-timeout 100000 --loglevel warn

COPY .browserslistrc jsconfig.json index.html vite.config.js ./
COPY public ./public
COPY src ./src
RUN pnpm run build

FROM nginx:alpine

ARG FQ_IMAGE_GIT_SHA=unknown

LABEL org.opencontainers.image.revision="${FQ_IMAGE_GIT_SHA}"
LABEL io.freshquant.git_sha="${FQ_IMAGE_GIT_SHA}"

COPY --from=build /fqwebui/web /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
