FROM node:lts-alpine AS build

RUN npm config set registry https://registry.npmmirror.com
RUN npm install -g pnpm

RUN pnpm config set fetch-retries 5 && \
    pnpm config set fetch-retry-mintimeout 20000 && \
    pnpm config set fetch-retry-maxtimeout 120000

WORKDIR /fqwebui
COPY ./morningglory/fqwebui .

RUN pnpm install --prefer-offline --fetch-timeout 100000 --loglevel verbose
RUN pnpm run build

FROM nginx:alpine

COPY --from=build /fqwebui/web /usr/share/nginx/html/
COPY ./morningglory/fqwebui/nginx.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
