[build-system]
requires = [
    "setuptools>=61.0",
    "Cython>=3.0,<4.0"
]
build-backend = "setuptools.build_meta"

[project]
name = "fqchan04"
version = "2026.5.24"
requires-python = ">=3.12,<3.13"

[tool.setuptools]
packages = ["demo"]

[tool.cibuildwheel]
build = ["cp39-*", "cp310-*", "cp311-*", "cp312-*", "cp313-*"]
skip = "*-musllinux_*"
environment = "PIP_INDEX_URL=https://mirrors.aliyun.com/pypi/simple PIP_TRUSTED_HOST=mirrors.aliyun.com"
