"""CLX daily A-share long-only portfolio matching fixture."""

from .engine import (
    PortfolioConfig,
    PortfolioInputError,
    PortfolioReconciliationError,
    run_portfolio,
    run_portfolios_shared,
)
from .fees import (
    DEFAULT_FEE_SCHEDULE,
    DEFAULT_SLIPPAGE_MODEL,
    FeeBreakdown,
    FeeSchedule,
    SlippageModel,
    StampTaxRule,
    TransferFeeRule,
)
from .limits import DEFAULT_LIMIT_SCHEDULE, LimitCheck, LimitRuleSchedule
from .models import (
    QUALITY_DEFAULT_LOT_SIZE,
    QUALITY_LIMIT_RULE_APPROXIMATE,
    QUALITY_STALE_CLOSE,
    BlockedReason,
    BlockedRecord,
    EquitySnapshot,
    FillRecord,
    LotEvent,
    MarketBar,
    OrderAttempt,
    OrderStatus,
    PendingOrderSnapshot,
    PortfolioRunResult,
    PositionSnapshot,
    Side,
    SignalDecision,
)

__all__ = [
    "DEFAULT_FEE_SCHEDULE",
    "DEFAULT_LIMIT_SCHEDULE",
    "DEFAULT_SLIPPAGE_MODEL",
    "QUALITY_DEFAULT_LOT_SIZE",
    "QUALITY_LIMIT_RULE_APPROXIMATE",
    "QUALITY_STALE_CLOSE",
    "BlockedReason",
    "BlockedRecord",
    "EquitySnapshot",
    "FeeBreakdown",
    "FeeSchedule",
    "FillRecord",
    "LimitCheck",
    "LimitRuleSchedule",
    "LotEvent",
    "MarketBar",
    "OrderAttempt",
    "OrderStatus",
    "PendingOrderSnapshot",
    "PortfolioConfig",
    "PortfolioInputError",
    "PortfolioReconciliationError",
    "PortfolioRunResult",
    "PositionSnapshot",
    "Side",
    "SignalDecision",
    "SlippageModel",
    "StampTaxRule",
    "TransferFeeRule",
    "run_portfolio",
    "run_portfolios_shared",
]
